In [87]:
import numpy as np
np.__version__

'2.1.3'

In [88]:
arr = np.zeros((3,2), dtype=float)
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
arr1 = np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
arr2 = np.empty((2,2))
arr2

array([[0.e+000, 0.e+000],
       [5.e-324, 5.e-324]])

In [91]:
x = np.arange(4, dtype=np.int64 )
y = np.full_like(x,6)
y

array([6, 6, 6, 6])

In [92]:
arr3 = np.arange(2,102,2)
arr3 



array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [93]:
arr4 = np.linspace(3,10,50)
arr4

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [94]:
arr5 = np.diag([1,2,3,4])
arr5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [95]:
! pip install pandas

In [96]:
import pandas as pd
df = pd.read_csv(r"students.csv")

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Name     10 non-null     object 
 1   Subject  10 non-null     object 
 2   Grade    9 non-null      float64
 3   Age      9 non-null      float64
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [98]:
df.head()

,Name,Subject,Grade,Age
0,Ahmed,Math,85.0,20.0
1,Sara,Math,90.0,21.0
2,Omar,Science,78.0,20.0
3,Lina,Math,92.0,22.0
4,Ahmed,Science,88.0,20.0


In [99]:
df.describe()

,Grade,Age
count,9.000000,9.000000
mean,86.111111,20.777778
std,6.392270,0.833333
min,76.000000,20.000000
25%,82.000000,20.000000
50%,88.000000,21.000000
75%,90.000000,21.000000
max,95.000000,22.000000


In [100]:
df[df["Grade"] > 85]

,Name,Subject,Grade,Age
1,Sara,Math,90.0,21.0
3,Lina,Math,92.0,22.0
4,Ahmed,Science,88.0,20.0
5,Sara,Science,95.0,21.0
7,Lina,Science,89.0,22.0


In [101]:
df.sort_values("Grade", ascending=False)

,Name,Subject,Grade,Age
5,Sara,Science,95.0,21.0
3,Lina,Math,92.0,22.0
1,Sara,Math,90.0,21.0
7,Lina,Science,89.0,22.0
4,Ahmed,Science,88.0,20.0
0,Ahmed,Math,85.0,20.0
6,Omar,Math,82.0,20.0
2,Omar,Science,78.0,20.0
9,Ali,Science,76.0,NaN
8,Yara,Math,NaN,21.0


In [102]:
df.isnull().sum()

Name       0
Subject    0
Grade      1
Age        1
dtype: int64

In [103]:
df= df.fillna({
    "Age" : df["Age"].mean(),
    "Grade" : df["Grade"].mean()
})

In [104]:
df["passed"] = df["Grade"].apply(lambda x: x >= 60)
df

,Name,Subject,Grade,Age,passed
0,Ahmed,Math,85.000000,20.000000,True
1,Sara,Math,90.000000,21.000000,True
2,Omar,Science,78.000000,20.000000,True
3,Lina,Math,92.000000,22.000000,True
4,Ahmed,Science,88.000000,20.000000,True
5,Sara,Science,95.000000,21.000000,True
6,Omar,Math,82.000000,20.000000,True
7,Lina,Science,89.000000,22.000000,True
8,Yara,Math,86.111111,21.000000,True
9,Ali,Science,76.000000,20.777778,True


In [107]:
df.to_csv("modified_students.csv")